Improve handling of multiple credentials
pytr-org/pytr pull request #144
Opened 2024-11-21 08:19 UTC by RealCLanger

Hi,

I'm taking another attempt to fix #38 (Session is not invalidated when a new login with different number occurs) which hits me as well. There has already be an effort in #56 but it seems that this went stale.

My idea is to store the cookies in a file that is named after the phone number which is the id of a trade republic account. So there can be no conflicts in cookies if the tool is used with multiple accounts.

I also remove the prompt that asks whether one would like to save the credentials and replace it with a command line option `--store_credentials` which defaults to true. I find this prompt rather annoying, especially for scripted calls of pytr.

Comments/Suggestions?

Cheers
Christoph

2024-11-24 23:30 UTC, pinzutu requested changes
That aside, being able to store multiple credentials seems like a useful feature to have👍

2024-11-24 23:30 UTC, pinzutu commented on pytr/account.py
> +def login(phone_no=None, pin=None, web=True, store_credentials=True):
```suggestion
def login(phone_no=None, pin=None, web=True, store_credentials=False):
```

2024-11-24 23:30 UTC, pinzutu commented on pytr/main.py
> +        default=True
I wouldn't save the credentials in a clear file per default when this behavior is not explicitly highlighted to the user.
```suggestion
```

2024-11-24 23:30 UTC, pinzutu commented on pytr/account.py
> +    tr = TradeRepublicApi(phone_no=phone_no, pin=pin, save_cookies=True)
Same critique here, the default behavior should not be to leave clear file cookies on your system indefinitely.
```suggestion
        else:
            save_cookies = False
            log.info("Credentials not saved")

    tr = TradeRepublicApi(phone_no=phone_no, pin=pin, save_cookies=save_cookies)
```

2025-01-06 20:50 UTC, RealCLanger commented
> That aside, being able to store multiple credentials seems like a useful feature to have👍

OK, I think that is a good suggestion. I changed the default to not store credentials. So one would need to explicitly turn that behavior on.

2025-01-29 21:55 UTC, merged