Add Dividende word in the filename
pytr-org/pytr pull request #45
Opened 2023-11-01 13:46 UTC by miry

Files from folder Abrechnung do not visible for Dividends. There are though Kauf and Verkauf names.

Make easy to filter files by name, add Dividende word to the file name and logs.

Example of logs:

    2023-11-01 14:44:26+0100 utils     INFO     36/60: Something Framework -- Sa. 14.10. um 00:07 Uhr (Europe/Kyiw) -- DIVIDENDE

Filename example: `Abrechnung/2023-10-13 00:07 Dividende - Something Framework.pdf`

2023-12-29 19:42 UTC, fredo-47 commented
I would like that too :smile:

2024-06-30 23:40 UTC, miry commented
@Katzmann1983 pls review. I have rebased against recent changes.

2024-07-02 14:35 UTC, Katzmann1983 requested changes

2024-07-02 14:35 UTC, Katzmann1983 commented on pytr/utils.py
> +            + f"{event['title']} -- {event['subtitle']}{isSavingsPlan_fmt} [{event["eventType"]}]"
File "/home/jens/Documents/7_krims_krams/14_traderepublic/pytr/pytr/utils.py", line 412
    + f"{event['title']} -- {event['subtitle']}{isSavingsPlan_fmt} [{event["eventType"]}]"
                                                                            ^
SyntaxError: f-string: unmatched '['

2024-07-02 14:35 UTC, Katzmann1983 commented on pytr/utils.py
> +                'CREDIT': 'Zinsen',  # It is equal to Dividende documents
I would suggest, storing it in a different folder, e.g. Dividende and adding another common dividend type

           'ssp_corporate_action_invoice_cash': 'Dividende',
                'INTEREST_PAYOUT_CREATED': 'Zinsen',
                'CREDIT': 'Dividende',

2024-07-02 14:36 UTC, Katzmann1983 commented on pytr/utils.py
> +            + f"{event['title']} -- {event['subtitle']}{isSavingsPlan_fmt} [{event["eventType"]}]"
It would be great to also remove the unneeded isSavingsPlan_fmt, when editing these lines. Could you please do that?

2024-07-02 16:46 UTC, miry commented on pytr/utils.py
> +            + f"{event['title']} -- {event['subtitle']}{isSavingsPlan_fmt} [{event["eventType"]}]"
fixed

2024-07-02 16:46 UTC, miry commented on pytr/utils.py
> +                'CREDIT': 'Zinsen',  # It is equal to Dividende documents
fixed

2024-07-02 16:46 UTC, miry commented
@Katzmann1983 Applied your suggestions.

2024-07-02 19:53 UTC, Katzmann1983 approved these changes

2024-07-02 19:56 UTC, merged

2024-07-02 19:57 UTC, Katzmann1983 commented
Thank you