No session resumption on different phone number
pytr-org/pytr pull request #56
Opened 2024-03-14 14:03 UTC by MartinScharrer

Added code to compare given phone number with the one in the credential file and disable websession resumption if so.
For this to work well I also added a command line option to select if credentials should be saved or not.
As a bonus a fix for corrupt cookie files got added.

This fixes issue #38.

2024-03-21 23:00 UTC, marzzzello commented on pytr/account.py
> +    save_credentials = (save_credentials == 'y')
Why not just use a boolean directly?

2024-03-21 23:02 UTC, marzzzello commented on pytr/main.py
> +    parser_login_args.add_argument('-s', '--save_credentials', choices=['y', 'n'], help='Save credentials')
Same here. I'd just remove choices and only save the credentials if the argument is passed (with `--save_credentials`)

2024-03-21 23:03 UTC, marzzzello requested changes
Thanks for your PR. I can merge after the argument is changed to bool

2024-04-04 08:24 UTC, MartinScharrer commented on pytr/main.py
> +    parser_login_args.add_argument('-s', '--save_credentials', choices=['y', 'n'], help='Save credentials')
I made the change to bool now. 
Should I remove the pre-existing ask_for_save code as well and only save them if the switch was used?

2024-07-02 13:45 UTC, Katzmann1983 commented
Using the current code, it seems that the active session is not correctly reused:
`pytr portfolio
15:41:45 Found credentials file
15:41:45 Phone: +346********, PIN: ****
15:41:45 Credentials not saved
15:41:45 Web session resumed
15:41:45 Logged in
15:41:45 Found credentials file
15:41:45 Phone: +346********, PIN: ****
15:41:45 Phone number different from credential files. Assuming different account.
15:41:45 Credentials not saved
Enter the code you received to your mobile app as a notification.
Enter nothing if you want to receive the (same) code as SMS. (Countdown: 31)
Code: 8415
15:42:11 Logged in
15:42:11 Connecting to websocket ...
15:42:12 Connected to websocket ...
`

2025-01-29 21:56 UTC, RealCLanger commented
I just merged #144, so closing this one.

2025-01-29 21:56 UTC, closed without merging